// Generated by CoffeeScript 1.10.0
var bookmarklet, filename, fs, pbcopy, source;

fs = require('fs');

filename = process.argv.slice(2)[0];

source = fs.readFileSync(filename, "utf8");

pbcopy = function(data) {
  var proc;
  proc = require('child_process').spawn('pbcopy');
  proc.stdin.write(data);
  return proc.stdin.end();
};

bookmarklet = source.replace(/^\s?javascript:/gm, "").replace(/^\s*\/\/.+/gm, "").replace(/^\s*\/\*[^]+?\*\/\n?/gm, "").replace(/\t/g, " ").replace(/[ ]{2,}/g, " ").replace(/^\s+/gm, "").replace(/\s+$/gm, "").replace(/\n/gm, "");

bookmarklet = "javascript:" + encodeURIComponent(bookmarklet);

console.log(bookmarklet);

if (/^darwin/.test(process.platform)) {
  pbcopy(bookmarklet);
}
